// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: add_custom_conversion.sql

package database

import (
	"context"
)

const addCustomConversion = `-- name: AddCustomConversion :exec
INSERT INTO user_conversions(start_type, end_type, exchange_rate)
	VALUES (?, ?, ?)
`

type AddCustomConversionParams struct {
	StartType    string
	EndType      string
	ExchangeRate float64
}

func (q *Queries) AddCustomConversion(ctx context.Context, arg AddCustomConversionParams) error {
	_, err := q.db.ExecContext(ctx, addCustomConversion, arg.StartType, arg.EndType, arg.ExchangeRate)
	return err
}
