// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: add_query_log_entry.sql

package database

import (
	"context"
)

const addQueryLogEntry = `-- name: AddQueryLogEntry :exec
INSERT INTO query_log (start_type, end_type, amount, dtg)
	VALUES (?, ?, ?, CURRENT_TIMESTAMP)
RETURNING id, start_type, end_type, amount, dtg
`

type AddQueryLogEntryParams struct {
	StartType string
	EndType   string
	Amount    string
}

func (q *Queries) AddQueryLogEntry(ctx context.Context, arg AddQueryLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, addQueryLogEntry, arg.StartType, arg.EndType, arg.Amount)
	return err
}
