// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: delete_custom_converstion.sql

package database

import (
	"context"
)

const deleteCustomConversion = `-- name: DeleteCustomConversion :exec
DELETE FROM user_conversions
WHERE (start_type = ?1 AND end_type = ?2)
	OR (start_type = ?2 AND end_type = ?1)
RETURNING conversion_id, start_type, end_type, exchange_rate, last_updated
`

type DeleteCustomConversionParams struct {
	StartType string
	EndType   string
}

func (q *Queries) DeleteCustomConversion(ctx context.Context, arg DeleteCustomConversionParams) error {
	_, err := q.db.ExecContext(ctx, deleteCustomConversion, arg.StartType, arg.EndType)
	return err
}
