// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_custom_conversion_options.sql

package database

import (
	"context"
)

const getCustomConversionOptions = `-- name: GetCustomConversionOptions :many
SELECT end_type FROM user_conversions
	WHERE start_type = ?
`

func (q *Queries) GetCustomConversionOptions(ctx context.Context, startType string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getCustomConversionOptions, startType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var end_type string
		if err := rows.Scan(&end_type); err != nil {
			return nil, err
		}
		items = append(items, end_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
