// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_starting_custom_options.sql

package database

import (
	"context"
)

const getStartingCustomOptions = `-- name: GetStartingCustomOptions :many
SELECT DISTINCT start_type FROM user_conversions
`

func (q *Queries) GetStartingCustomOptions(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getStartingCustomOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var start_type string
		if err := rows.Scan(&start_type); err != nil {
			return nil, err
		}
		items = append(items, start_type)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
