// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_conversion_count.sql

package database

import (
	"context"
)

const getConversionCount = `-- name: GetConversionCount :one
SELECT COUNT(*) FROM query_log
	WHERE start_type = ? AND end_type = ?
`

type GetConversionCountParams struct {
	StartType string
	EndType   string
}

func (q *Queries) GetConversionCount(ctx context.Context, arg GetConversionCountParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getConversionCount, arg.StartType, arg.EndType)
	var count int64
	err := row.Scan(&count)
	return count, err
}
