// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_custom_exchange_rate.sql

package database

import (
	"context"
)

const getCustomExchangeRate = `-- name: GetCustomExchangeRate :one
SELECT exchange_rate FROM user_conversions
	WHERE start_type = ? AND end_type = ?
`

type GetCustomExchangeRateParams struct {
	StartType string
	EndType   string
}

func (q *Queries) GetCustomExchangeRate(ctx context.Context, arg GetCustomExchangeRateParams) (float64, error) {
	row := q.db.QueryRowContext(ctx, getCustomExchangeRate, arg.StartType, arg.EndType)
	var exchange_rate float64
	err := row.Scan(&exchange_rate)
	return exchange_rate, err
}
