// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type CurrencyExchange struct {
	ConversionDirection string
	ExchangeRate        float64
	LastUpdated         sql.NullTime
}

type QueryLog struct {
	ID        int64
	StartType string
	EndType   string
	Amount    string
	Dtg       sql.NullTime
}

type UserConversion struct {
	ConversionID int64
	StartType    string
	EndType      string
	ExchangeRate float64
	LastUpdated  sql.NullTime
}
