// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: set_currency_rate.sql

package database

import (
	"context"
)

const setCurrencyRate = `-- name: SetCurrencyRate :exec
UPDATE currency_exchange
SET exchange_rate = ?, last_updated = CURRENT_TIMESTAMP
WHERE conversion_direction = ?

RETURNING conversion_direction, exchange_rate, last_updated
`

type SetCurrencyRateParams struct {
	ExchangeRate        float64
	ConversionDirection string
}

func (q *Queries) SetCurrencyRate(ctx context.Context, arg SetCurrencyRateParams) error {
	_, err := q.db.ExecContext(ctx, setCurrencyRate, arg.ExchangeRate, arg.ConversionDirection)
	return err
}
