// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: update_custom_exchange.sql

package database

import (
	"context"
)

const updateCustomExchange = `-- name: UpdateCustomExchange :exec
UPDATE user_conversions
SET exchange_rate = ?
WHERE start_type = ? AND end_type = ?
`

type UpdateCustomExchangeParams struct {
	ExchangeRate float64
	StartType    string
	EndType      string
}

func (q *Queries) UpdateCustomExchange(ctx context.Context, arg UpdateCustomExchangeParams) error {
	_, err := q.db.ExecContext(ctx, updateCustomExchange, arg.ExchangeRate, arg.StartType, arg.EndType)
	return err
}
